### ISSUE TITLE
Firefox and arrow keys

### ISSUE THREAD

**Issue by ubmarco** [Rob--W/grab-to-pan.js#10]
Hi,
I'm a bit puzzled about the behavior of the library on Firefox 86.0 (64-bit).
When loading the demo https://rob--w.github.io/grab-to-pan.js/demo.html I can initially not use the arrow keys or page-up/down to navigate the scroll div. However when deactivating 'Activate Grab to Pan' setting and clicking into the box, I can use the arrow keys. They continue to work also when re-activating 'Gab to Pan'.
I recorded a screencast:
![Peek 2021-03-01 10-04](https://user-images.githubusercontent.com/839934/109475740-5bcfb280-7a76-11eb-9e17-6487981b9667.gif)

On Chrome however the keys work from the beginning when  'Grab to Pan' is active. Can anyone reproduce that? Why would Firefox behave that way?
Background: I'm doing a custom implementation of pdf.js that uses this library and I'm seeing the same behavior in my app.

Thanks for any help on this!

**Comment by ubmarco** [comment]
When running `document.getElementById('scrollable-container').focus()` in the Firefox Console the arrow keys work right from the beginning. Also when I just click on the white `<body>` area outside the `scrollable-container` div, scrolling works. Seems like Firefox is initially not aware of a scrollable div inside `<body>`.

Maybe this issue has nothing to do with this library.
Any opinions?

**Comment by Rob--W** [comment]
The library does not bind any key handlers. What you're observing is the default behavior of the browser.

It seems that initially, the document is not focused (but the `activeElement` is `<body>`).
After clicking, the document is focused, and although `<body>` is still the `activeElement`, the scrollable area scrolls in response to arrow keys. If you think that this is a bug, file a new bug report at https://bugzilla.mozilla.org/
