### ISSUE TITLE
onmousedown onmouseup activate and deactivate

### ISSUE THREAD

**Issue by mhulse** [Rob--W/grab-to-pan.js#5]
Hello,

First, I want to say that this code is a life saver! Thank you for writing and sharing it! 👍 

I ran into a situation where I need to activate/deactivate only when clicking and dragging on a background object (in this case, a direct child of the scrollable area).

My code:

```js
var grid = document.getElementById('grid'); // Child of `#canvas`.
var g2p = new GrabToPan({
	element: document.getElementById('canvas'),
	onActiveChanged: function(isActive) {
		console.log('Grab-to-pan is ' + (isActive ? 'activated' : 'deactivated'));
	}
});
//g2p.activate();

grid.addEventListener('mousedown', function() {
	
	g2p.activate();
	
}, false);

grid.addEventListener('mouseup', function() {
	
	g2p.deactivate();
	
}, false);
```

In the console, I get:

```text
Grab-to-pan is activated
Grab-to-pan is deactivated
```

I think the issue is that `g2p` activates on click, so the `mousedown` only works if you click once and click again (that is, you have to remove the `mouseup`).

I can think of a few fixes (like calling `click` inside `mousedown`) or doing something with `hover` detection.

Anyway, just thought I'd report. Not sure if you would consider this an issue.

**Comment by mhulse** [comment]
This appears to work:

```js
grid.addEventListener('mouseover', function(event) {
	
	if (event.target.id == 'grid') {
		g2p.activate();
	} else {
		g2p.deactivate();
	}
	
});
```

Just in case anyone else runs into a similar situation. 👍

**Comment by Rob--W** [comment]
`_onmousedown` is an internal implementation detail, but you could also delegate the event to GrabToPan as follows:

```javascript
grid.addEventListener('mousedown', function(event) {
    g2p.activate();
    g2p._onmousedown(event);
}, false);
```

**Comment by mhulse** [comment]
> _onmousedown is an internal implementation detail, but you could also delegate the event to GrabToPan as follows:

Ooooh, nice! Thanks for the help and the code example.

Since the options to get this working are pretty quick and easy, I figure I'll close the issue now.

Thanks again for your help and for the life-saving code!
