### ISSUE TITLE
CSS_CLASS_GRABBING undefined on <html>

### ISSUE THREAD

**Issue by mhulse** [Rob--W/grab-to-pan.js#6]
https://github.com/Rob--W/grab-to-pan.js/blob/b81897bee4f08daf0bf7539ceb207ed09e472a7b/grab-to-pan.js#L150

Not sure if this line of code is even needed as the "overlay" appears to handle everything related to cursor change/display.

If this class is needed (`grab-to-pan-grabbing`) then, should it toggle on/off as the class name implies action of "grabbing", whereas `.grab-to-pan-grab` implies initialization (i.e., always on, initialized on element).

I can do a PR if given a little direction. :)

**Comment by Rob--W** [comment]
Good catch - the line should be removed.
I overlooked it when I removed it as a part of https://github.com/Rob--W/grab-to-pan.js/commit/e0f893753ac10a5c97159fd01155b05d234f4c0f

Want to make a PR and remove that line?

**Comment by mhulse** [comment]
> Want to make a PR and remove that line?

Yup, doing now.
