### ISSUE TITLE
scroll-behavior: smooth;

### ISSUE THREAD

**Issue by mhulse** [Rob--W/grab-to-pan.js#9]
This is not a deal breaker by any means, just thought I would report the issue for future reference. @Rob--W, feel free to close this after reading.

When adding the css property [`scroll-behavior: smooth;`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) to `.scrollable`, Firefox disables vertical scrolling:

![screenshot 2016-10-11 13 34 23](https://cloud.githubusercontent.com/assets/218624/19287669/96035cf8-8fb7-11e6-9ece-b8becb60dfa4.png)

The fix is to not use that property.

Just thought it was an interesting observation.

**Comment by Rob--W** [comment]
This report actually helps, thanks!

I searched on bugzilla for "scroll-behavior", and found a reference to the `element.scrollBy` method at https://bugzil.la/1308775. Apparently the method was introduced as a part of CSSOM in https://bugzil.la/1045754. Unfortunately it is not documented (there is a dev-doc-needed label on that bug, but nobody worked on it). Naturally, I expected a `element.scrollTo` method to exist, and indeed it does. So I will fix this.

**Comment by mhulse** [comment]
Wow, nice sleuthing and fix! Thanks for patching that, and for doing it so quickly! 👍 

I really appreciate it Rob! This code has been a life saver. :)
